/* Auto-generated by findtables.c  */
#ifndef PETSCII_CHARTRANSFORM_H
#define PETSCII_CHARTRANSFORM_H

#include <exec/types.h>

/*
 * Character transformation tables.
 * table[charIndex] = index of the char that is the
 * transformation of charIndex in the same charset.
 * Returns charIndex itself when no good match was found.
 */

extern const UBYTE petsciiUpperFlipX[256];
extern const UBYTE petsciiUpperFlipY[256];
extern const UBYTE petsciiUpperRot90[256];
extern const UBYTE petsciiUpperRotN90[256];
extern const UBYTE petsciiUpperRot180[256];

extern const UBYTE petsciiLowerFlipX[256];
extern const UBYTE petsciiLowerFlipY[256];
extern const UBYTE petsciiLowerRot90[256];
extern const UBYTE petsciiLowerRotN90[256];
extern const UBYTE petsciiLowerRot180[256];

#endif /* PETSCII_CHARTRANSFORM_H */
